@baseUrl = http://localhost:3000

###
GET {{ baseUrl }}

###
GET {{ baseUrl }}/test

###
GET {{ baseUrl }}/health


### Middleware no encontrado
GET {{ baseUrl }}/healthd


### Relacion 1 : N
GET {{ baseUrl }}/directores

### 
POST {{ baseUrl }}/directores
Content-Type: application/json

{
    "nombre": "Denis Villeneuve"
}


### 
POST {{ baseUrl }}/peliculas
Content-Type: application/json

{
    "titulo": "Dune",
    "anio": 2021,
    "directorId": 3
}



### LIsta peliculas con director y genero
GET {{ baseUrl }}/peliculas


### Eliminar director, probar borrado en cascada

DELETE {{ baseUrl }}/directores/6